"""use1 table

Revision ID: 13cdc1e6565c
Revises: fb8f8f468514
Create Date: 2018-09-05 14:48:23.569248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cdc1e6565c'
down_revision = 'fb8f8f468514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catinfo', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_catinfo_status'), 'catinfo', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catinfo_status'), table_name='catinfo')
    op.drop_column('catinfo', 'status')
    # ### end Alembic commands ###
