"""use table

Revision ID: fb8f8f468514
Revises: 
Create Date: 2018-09-05 11:23:44.510515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8f8f468514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catinfo_headimage'), 'catinfo', ['headimage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catinfo_headimage'), table_name='catinfo')
    # ### end Alembic commands ###
